spring.application.name=JobPortal
spring.datasource.url=jdbc:postgresql://localhost:5432/Ecom-proj
spring.datasource.username=postgres
spring.datasource.password=Deva@#2006


spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update